### ISSUE TITLE
Create Navbar Profile component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#3]
Create the navbar profile component which should have an “icon” like shape, and the username. The component should receive the following parameters: username. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="414" alt="Screenshot 2024-12-12 at 01 16 11" src="https://github.com/user-attachments/assets/3e0b1ade-3a39-4fd6-b36b-a18a752f4b3c" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Kingsuite** [comment]
Could I take a shot at this?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Supa-mega** [comment]
Mind if I try this one?

**Comment by ussyalfaks** [comment]
GF, I would love to work on this. I am Usman, and I have solid experience in JavaScript, TypeScript, and React. I'm confident I can contribute effectively to this task.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by kayceeDev** [comment]
I’d like to work on this.

**Comment by Kachimercy1** [comment]
May I take this issue on?

**Comment by anonfedora** [comment]
I'm fullstck blockchain developer, proficient in Reactjs, Cairo, Rust, Nextjs, Nestjs

Will check the figma design if available to implement the Navbar profile component as required following best practices.

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
Mind if I take this issue?

**Comment by chigozzdevv** [comment]
I'd love to give this a go.

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Belloabraham121** [comment]
Hi, I'm Iteooluwakisi!

I am a member of Web3Bridge and an experienced frontend developer proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
I have previously contributed to several projects, including:

CoinSafe: A DeFi startup built on Lisk.
Scaffold-ETH: A popular development framework for Ethereum.
BuidlGuidl: A community-focused platform for Ethereum builders.
I’m confident in my ability to tackle this issue and contribute effectively to the project.

Plan to Solve the Issue

Familiarize with the Codebase

Review the existing structure and functionality of the codebase.
Identify key components and dependencies relevant to the issue.
Understand the Problem

Carefully analyze the issue details to clarify the requirements.
Explore any linked resources or documentation to gain a comprehensive understanding.
Implement the Solution

Develop a solution leveraging my technical skills and experience.
Test thoroughly to ensure functionality and resolve edge cases.
Collaborate and Communicate

Reach out to the relevant group/chat for clarifications if needed.
Engage proactively to avoid delays and ensure alignment with project goals.
Submit and Refine

Open a Pull Request (PR) with detailed descriptions and documentation.
Address feedback promptly and make any necessary adjustments.
Looking forward to contributing and learning!

**Comment by 3th-Enjay** [comment]
I'd love to give this a go.

**Comment by Dorcas18** [comment]
Could I take over this issue?

**Comment by Nityam573** [comment]
I’m interested in this one.
