### ISSUE TITLE
Create Button with Functionality component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#4]
Create the button with functionality component which should have some text. The component should receive the following parameters: text and the function to call when the button is clicked. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="453" alt="Screenshot 2024-12-12 at 01 17 54" src="https://github.com/user-attachments/assets/c7408f01-0ca6-4890-8ea4-267a9c39319f" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by 3th-Enjay** [comment]
Mind if I try this one?

**Comment by kayceeDev** [comment]
I'd like to handle this task.

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by Prosper1218** [comment]
hello, i'm prosper, A frontend/Blockchain Developer. 
can i cook this for you ?? I Know I'll deliver.
I'll take a maximum of 24hrs to get this done.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchttps://mattedsgn.com/himebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ Would love to tackle this!

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by emmz3230** [comment]
Could I grab this task?


I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue and my ETA is 8 hours

**Comment by kcmikee** [comment]
I am kcmikee, a frontend developer with 4+ years of experience working with React, Next.js, and TypeScript. I am a graduate of Web3bridge Africa, where I got to dive deep into blockchain development and contribute to some cool web3 projects. I have also made significant contributions to open-source projects and am eager to bring that expertise to this project.
My approach to this task will include:
1. Reviewing the project structure, Figma designs, and any relevant files.
2. Implementing the button, ensuring it adheres to the application's color scheme and branding.
3. Make sure it doesn't affect the application performance
Estimated Time (ET): 1 day.

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 hacks.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

* GitHub: https://github.com/Bran18?tab=repositories
* OnlyDust: https://app.onlydust.com/u/Bran18
* X https://x.com/branfdez_18
* LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by khayss** [comment]
Let me handle this issue!

With my frontend development skills, I can easily implement this Button component with the required functionality.
It's straightforward. I'll describe the specified props while creating the component and use this props to implement the desired functionality of this component.

**Comment by Dorcas18** [comment]
Can I jump on this task?

**Comment by Nityam573** [comment]
Let me handle this issue!

**Comment by bitfalt** [comment]
Closed by #22
