### ISSUE TITLE
Create Post Profile component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#6]
Create the Post Profile component which should have an “icon” like shape, the username and the user’s role. The component should receive the following parameters: username and user’s role. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="638" alt="Screenshot 2024-12-12 at 01 22 14" src="https://github.com/user-attachments/assets/e93ddd20-fbc1-4483-ac81-af390243e2b8" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by NueloSE** [comment]
Could I take a shot at this?

**Comment by kayceeDev** [comment]
Mind if I try this one?

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by akintewe** [comment]
Hi, I'm interested in taking on the this task. I am a frontend/ UIUX developer and i have experience in working with detailed designs. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you. ETA 8hours :)

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by chigozzdevv** [comment]
Can I take this from here?

**Comment by mimisavage** [comment]
Can I attempt this issue?

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

Additionally, I’m a Gold Contributor with over 15 merged PRs, showcasing my commitment to open-source development and collaborative problem-solving.

To tackle this issue:
I’ll create a Post Profile component that includes an “icon,” username, and user’s role. The component will accept username and user’s role as props and will use the provided color palette for styling. The design will match the provided example image and be fully responsive.

ETA: 12-48 hours. Feel free to reach out via Telegram.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by suhas-sensei** [comment]
May I take this issue on? I'll create a reusable Post Profile component with an icon, username display, and role indicator using a consistent color palette. 
Having experience with React component design, I'll ensure proper prop handling and styling while maintaining component reusability

**Comment by emarc99** [comment]
Mind if I try this one?

**Comment by SudiptaPaul-31** [comment]
Can I work on this, please?

**Comment by khayss** [comment]
Could I try solving this?

As a full-stack developer who has good experience working on frontend projects, I can handle this issue.

I'll design this component, adding the required props, implement a responsive styling and make it available to be used seamlessly in the required section of the app.

**Comment by Dorcas18** [comment]
Can I take care of this issue?

**Comment by Nityam573** [comment]
Could I take on this issue?
