### ISSUE TITLE
Create Navbar Item component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#8]
Create the Navbar Item component which should have text. The component should receive the following parameters: text and the route (function) to where it should lead the user to once it is clicked. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="260" alt="Screenshot 2024-12-12 at 01 24 06" src="https://github.com/user-attachments/assets/b6577a3a-784e-4335-8c7b-f3e33a8f3efc" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 0xdevcollins** [comment]
May I pick this up?

I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Kachimercy1** [comment]
May I take this issue on?

**Comment by Kingsuite** [comment]
I’d like to work on this.

**Comment by 3th-Enjay** [comment]
May I be assigned to this?

**Comment by kayceeDev** [comment]
Can I jump on this task?

**Comment by ShantelPeters** [comment]
Would love to tackle this!

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I believe this is an excellent first issue for me to contribute to. Can take on this task?

ETA: 24 hrs

**Comment by mimisavage** [comment]
May I handle this issue?

**Comment by emmz3230** [comment]
Can I start working on this?

I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

**Comment by Villarley** [comment]
Hi👋🏻
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
To tackle this issue:
I’ll create a Navbar Item component that accepts text and route as props. The component will use the provided color palette for styling and navigate the user to the specified route when clicked.

ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by morelucks** [comment]
My name is Kamshak Lucky Isuwa, and I am excited to apply for the frontend developer role to create the Navbar Item component. With extensive experience in React.js, Next.js, JavaScript, and modern frontend practices, I am confident in delivering a polished and functional component within 24 hours, adhering to the provided color palette and design guidelines.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 hacks.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

* GitHub: https://github.com/Bran18?tab=repositories
* OnlyDust: https://app.onlydust.com/u/Bran18
* X https://x.com/branfdez_18
* LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Dorcas18** [comment]
Can I start working on this?
