### ISSUE TITLE
Create DAO Creation Progress component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#9]
Create the DAO Creation Progress component which should have a static text (Create your DAO), step progress, the progress bar component, a title and description. The component should receive the following parameters: step progress, title, and description. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="717" alt="Screenshot 2024-12-12 at 01 27 06" src="https://github.com/user-attachments/assets/d6edacd3-5fb2-4b89-888f-d57d47c6be0a" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Yunusabdul38** [comment]
I’d like to work on this.

**Comment by CollinsC1O** [comment]
Can I tackle this one?

**Comment by kayceeDev** [comment]
Could I take on this issue?

**Comment by derianrddev** [comment]
**Hello SocialSphere team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your Stellar-based project during the **Only Dust 11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue*

1. Design a functional React component that includes:
    - Static text: **"Create your DAO"**.
    - A step progress indicator.
    - The progress bar.
    - A dynamic title and description received as parameters.
2. Use the provided color palette to ensure visual consistency.
3. Ensure the component is fully responsive and accessible.
4. Validate the final design using the reference image.
5. Test the component to ensure the parameters (step progress, title, and description) render correctly.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by sandragcarrillo** [comment]
Would love to contribute to this project, I'm a fan of the DAO space and love that you are building this. I have created similar smaller projects for Hackathons so I'm kind of familiar with this type of components. 

I have experience as frontend developer and blockchain developer, so I believe I could solve this issue, I would take the Figma component design as the guide to create it using the color pallette.

ETA: 1-3 days

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by akintewe** [comment]
Hi, I'm interested in taking on the this task. I am a frontend/ UIUX developer and i have experience in working with detailed designs. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you. ETA 8hours :)

**Comment by ShantelPeters** [comment]
Let me handle this issue!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by SudiptaPaul-31** [comment]
I'm Sudipta Paul a fullstack and blockchain developer for more than 1.5years and worked on many projects from previous odhack and my profile : (https://app.onlydust.com/u/SudiptaPaul-31)

My approach:
Will start by creating a new component and add it on the web page with proper styling and responsive and to check the progress is working perfectly or not

**Comment by khayss** [comment]
I'll like to be considered for this task.

I'm a full-stack developer with good experience building frontend projects.

I have gone through the issue description and have a proper understanding on how to implement this component to meet the specifications.

**Comment by Dorcas18** [comment]
May I take care of this?

**Comment by Nityam573** [comment]
Can I take this from here?

**Comment by pheobeayo** [comment]
Would love to tackle this!

**Comment by bitfalt** [comment]
Closed by #27
